// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqndxlcznznqgiyefzef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbmR4bGN6bnpucWdpeWVmemVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDYyNDUsImV4cCI6MjA3MzE4MjI0NX0.lEG3AxsjiqYKt9YdnBJhzKa0IDfuzWrjsOLfzuxVEe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});